site_name: Curso de Python
nav:
  - 'Algoritmos':
    - 'Shortest Path':
      - 'Inicio': '02_algoritmos/shortest_path/intro.md'
  - 'High Performance Python':
    - 'Introducción': '05_hpc/intro.md'
  
theme:
  name: material
site_description: Un sitio para aprender Python
site_author: Jose Alonzo
plugins:
  - search
  - mermaid2
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg-full.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML
markdown_extensions:
  - smarty
  - mdx_math
  - pymdownx.arithmatex
  - pymdownx.highlight