site_name: Curso de Algoritmos y Estructuras de Datos con Python
site_description: Un sitio para aprender Python y Algoritmos
site_author: Jose Alonzo
nav:
  - 'Algoritmos':
    - 'Shortest Path':
      - 'Inicio': '02_algoritmos/shortest_path/intro.md'
    # - 'Timeline': 
    - 'Patrones DP':
      - 'Secuencia de Fibonacci': '05_problem_solving/dp_01_fibonacci.md'
      # - 'Algoritmoa de Kadane': ''
      # - '0/1 Knapsack': ''
      # - 'Knapsack sin limites': ''
      # - 'Longest Common Subsequence ': ''
      # - 'Longest Increasing Subsequence': ''
      # - 'Palindromic Subsequence': ''
      # - 'Edit Distance': ''
      # - 'Subset Sum': ''
      # - 'String Partition': ''
      # - 'Número de Catalan': ''
      # - 'Matrix Chain Multiplication': ''
      # - 'Count Distinct Ways': ''
      # - 'DP en Grids': ''
      # - 'DP en Trees': ''
      # - 'DP en Graphs': ''
      # - 'Digit DP': ''
      # - 'Bitmasking DP': ''
      # - 'Probability DP': ''
      # - 'State Machine DP': ''
  - 'High Performance Python':
    - 'Introducción': '05_hpc/intro.md'
  
theme:
  name: material
  features:
    - content.code.annotate
    - content.code.copy
    - content.code.select
  palette:
    scheme: slate
    primary: indigo
    accent: indigo
  highlightjs: true
  hljs_languages:
    - yaml
    - python
    - typespec
    - rust
  collapse_navigation: True
  locale: es
plugins:
  - search
  - mermaid2
  - glightbox
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg-full.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML
markdown_extensions:
  - smarty
  - mdx_math
  - pymdownx.arithmatex
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption